<?php

/**
 * Copyright (c) 2014 Jacek Kobus <kobus.jacek@gmail.com>
 * See the file LICENSE.txt for copying permission.
 */

namespace PHPExtra\Proxy\Http;

use PHPExtra\Proxy\SymfonyBridge\AbstractRequest;

/**
 * The Request class
 *
 * @author Jacek Kobus <kobus.jacek@gmail.com>
 */
class Request extends AbstractRequest
{
    /**
     * Creates a Request based on a given URI and configuration.
     *
     * The information contained in the URI always take precedence
     * over the other information (server and parameters).
     *
     * @param string $uri        The URI
     * @param string $method     The HTTP method
     * @param array  $parameters The query (GET) or request (POST) parameters
     * @param array  $cookies    The request cookies ($_COOKIE)
     * @param array  $files      The request files ($_FILES)
     * @param array  $server     The server parameters ($_SERVER)
     * @param string $content    The raw body data
     *
     * @return $this
     */
    public static function create(
        $uri,
        $method = 'GET',
        $parameters = array(),
        $cookies = array(),
        $files = array(),
        $server = array(),
        $content = null
    ) {
        return parent::create(
            $uri,
            $method,
            $parameters,
            $cookies,
            $files,
            $server,
            $content
        ); // TODO: Change the autogenerated stub
    }

    /**
     * Creates a new request with values from PHP's super globals.
     *
     * @return $this
     */
    public static function createFromGlobals()
    {
        return parent::createFromGlobals(); // TODO: Change the autogenerated stub
    }


}